version: '3.7'
services:
  flyway:
    image: boxfuse/flyway
    restart: always
    command: -url=jdbc:postgresql://db:5432/foo -user='postgres' -password='test123' -schemas='bar' migrate
    volumes:
    - .:/flyway/sql
    depends_on:
    - db

  db:
    image: tgalati1122/flyway_seeded_postgres
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: 'test123'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'foo'
    ports:
    - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    depends_on:
    - db
